name: Code standard

on:
  push:
    branches:
      - "*" # matches every branch that doesn't contain a '/'
      - "*/*" # matches every branch containing a single '/'
      - "**" # matches every branch
      - "!master" # excludes master
jobs:
  flake8-lint:
    runs-on: self-hosted
    name: Checking for linting issues.
    steps:
      - name: Check out source repository
        uses: actions/checkout@v2
      - name: Set up Python environment
        uses: actions/setup-python@v2
        with:
          python-version: "3.10.5"
          architecture: x64
      - name: flake8 Lint
        uses: py-actions/flake8@v2
        with:
          ignore: "F401,W0703,E203,BLK100"
          max-line-length: "130"
          path: ""
          plugins: "flake8-bugbear==22.1.11"
